#!/bin/bash

PASSED=1

ensure_verifies()
{
  # Function. Parameter 1 is the return code
  # Para. 2 is the name of the benchmark.
  if [ "${1}" -ne "0" ]; then
    echo -e "\rFailed benchmark ${2}.    "
    echo "*** ERROR: Benchmark ${2} expected to verify, but did not verify."
    PASSED=0
  else
    echo -e "\rPassed benchmark ${2}.    "
  fi
}

ensure_fails()
{
  # Function. Parameter 1 is the return code
  # Para. 2 is the name of the benchmark.
  if [ "${1}" -ne "1" ]; then
    echo -e "\rFailed benchmark ${2}.    "
    echo "*** SOUNDNESS ERROR ***************************************"
    echo "*** SOUNDNESS ERROR: Benchmark ${2} expected to fail, but verified!"
    echo "*** SOUNDNESS ERROR ***************************************"
    PASSED=0
  else
    echo -e "\rPassed benchmark ${2}.    "
  fi
}

while (( "$#" )); do
    echo -ne "Checking benchmark ${1}..."
    ulimit -St 60
    ./grasshopper.native $2 $OPTIONS 2> /dev/null
    res=$?
    ulimit -St unlimited
    if [ $3 == "pass" ]; then
        ensure_verifies $res $1
    else
        ensure_fails $res $1
    fi
    shift
    shift
    shift
done
if [ $PASSED == 1 ]; then
    echo "All tests passed."
else
    echo "There were failing test cases."
fi